//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 仓储管理系统.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstoreOrder
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int WarehouseId { get; set; }
        public int SupplierId { get; set; }
        public int MemberId { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    }
}
