//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 仓储管理系统.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WarehouseDBEntities : DbContext
    {
        public WarehouseDBEntities()
            : base("name=WarehouseDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Instore> Instore { get; set; }
        public virtual DbSet<InstoreOrder> InstoreOrder { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<Outstore> Outstore { get; set; }
        public virtual DbSet<OutstoreOrder> OutstoreOrder { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<UserMenu> UserMenu { get; set; }
    }
}
